### ISSUE TITLE
better recovery mechanism from missing channel in `compare-versions`

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#109]
Currently within `compare-versions`, if the script fails to download the latest channel published, it automatically tries to regenerate a channel with the latest versions, which isn't exactly desirable, since they may not be compatible. ([source code](https://github.com/FuelLabs/fuelup/blob/5be44161b436ae4890b1b08b6f8c623b9768fceb/scripts/compare-versions/src/main.rs#L133-L153))

Better way to handle this:
1) Ensure that the error is a 404 error, and not due to other issues eg. connectivity issues
2) Only if the error is a 404 error, we use the published incompatible versions to get the last published one, perhaps by querying the list of versions using GitHub API and comparing. Alternatively we could also have a separate folder where we publish all past compatible versions, similar to our incompatible versions. Then we can simply take the latest versions there. The 2nd method seems to be more straightforward.

**Comment by mh6005** [comment]
Ok
