### ISSUE TITLE
re-define and re-implement `latest` channel

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#116]
The `latest` channel should consist of the _latest_ binaries of `forc` and `fuel-core`, and the current workflow that we have running tests should produce the `stable` channel instead.

To accomplish this:

1.  Bring back the previous workflow that indexes the latest versions without running tests. This workflow should also run every 30 minutes.
2. Rename the current workflow and tweak configs to create the `stable` channel instead of the `latest` channel

**Comment by mitchmindtree** [comment]
Going to close this as soon after this comment was posted, @bingcicle and I decided it's best to keep the existing terminology. See [this table](https://github.com/FuelLabs/fuelup/issues/118#issue-1317695819) for a brief overview of toolchain definitions.
