### ISSUE TITLE
Include a markdown table in `CHANNELS.md` or `README.md` as a high-level overview of the available channels

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuelup#118]
Perhaps it could be useful to have something like this in `CHANNELS.md` or even the `README.md`?

| Channel | Source | Integration Tested | Update Frequency | Available |
| --- | --- | --- | --- | --- |
| **latest** | Published bins. | :heavy_check_mark: | Checks every 30 min. | :heavy_check_mark: |
| **nightly** | `master` branch. | :heavy_check_mark: | Nightly. | :heavy_minus_sign: |
| **beta** | Published bins. | :heavy_check_mark: | 6 Week Cycle. | :heavy_minus_sign: |
| **stable** | Published bins. | :heavy_check_mark: + successful beta | 6 Week Cycle. | :heavy_minus_sign: |

Could update these in the future to use badges that link to the latest github workflow for each, and maybe provide another column that shows the current versions released under each channel.

**Comment by bingcicle** [comment]
I think now that we have more than just `README.md` as a doc, maybe this is a good time to finally introduce an mdbook for `fuelup` #3 that contains all the info here.
