### ISSUE TITLE
The Fuelup Book link is broken in the README file

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuelup#143]
The link points to https://fuellabs.github.io/fuelup/master/introduction/index.html which doesn't work. It should probably be just https://fuellabs.github.io/fuelup/master/index.html

The "install from source" link is also broken. It points to https://fuellabs.github.io/sway/latest/introduction/installation.html#installing-from-source but should point to https://fuellabs.github.io/sway/master/introduction/installation.html#installing-from-source until `latest` can somehow be used in a link.

**Comment by bingcicle** [comment]
Thanks for reporting this!
