### ISSUE TITLE
Update `fuelup check --verbose` to print `forc-client`

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#145]
~`fuelup check --verbose` currently does not show `forc-client` version.~

Correction: it does show the versions of `forc-deploy` and `forc-run` separately:

![Screenshot 2022-08-19 at 8 18 14 PM](https://user-images.githubusercontent.com/25565268/185616751-766b2591-4002-451f-b250-905987878e6b.png)
 
Do we want to keep this, or combine both using logic in `fuelup check` into `forc-client`?

**Comment by kayagokalp** [comment]
I think it would be cool to have `forc-client` as a level there, like:

```md
forc - Up to date : 0.20.2
  - forc-fmt - Up to date : 0.20.2
  - forc-lsp - Up to date : 0.20.2
  - forc-explore - Up to date : 0.20.2
  - forc-client - Up to date : 0.20.2
    - forc-run
    - forc-deploy
```

or we can even drop `run` and `deploy` and just show the parent's name, i.e `forc client` :eyes:

**Comment by bingcicle** [comment]
hmm, while we can just show `forc-client` it might be confusing since the actual binary names are `forc-deploy` and `forc-run`.

How about:

```
forc - Up to date : 0.20.2
  - forc-fmt - Up to date : 0.20.2
  - forc-lsp - Up to date : 0.20.2
  - forc-explore - Up to date : 0.20.2
  - forc-client
    - forc-run - Up to date : 0.20.2
    - forc-deploy - Up to date : 0.20.2
```

I think this shows clearly that `forc-run` and `forc-deploy` are separate binaries, while still showing that they're packaged under `forc-client` as one.

**Comment by kayagokalp** [comment]
That looks good to me!
