### ISSUE TITLE
Add possibility to uninstall/remove installed toolchains

### ISSUE THREAD

**Issue by itspauloroberto** [FuelLabs/fuelup#161]
### Problem you are trying to solve

When you read the `fuelup toolchain --help` description you can read that it installs new toolchains or modify/query installed toolchains, but there is no option to remove one.

You can easily install a new toolchain by typing `fuelup toolchain install` but there is nothing like `fuelup toolchain uninstall`.

I see it as a problem since you may want to just remove it instead of modifying it and you are not able to.

### Solution you'd like

A new command called `fuelup toolchain uninstall <name>`, and also an updated description for --help.

### Notes

I have found this issue when i was trying to remove latest version of fuel-core to install a previous one.

**Comment by bingcicle** [comment]
Hey there! Thanks for opening an issue!

Do you happen to have an older version of `fuelup`? `v0.3` should have the `fuelup toolchain uninstall` function.

**Comment by itspauloroberto** [comment]
You're welcome. I was just trying to help others that had the same problem. But it seems, that for some reason my fuelup was at version 0.2.3, which I am not sure the reason behind it since I was following the quickstart provided here (https://fuellabs.github.io/fuels-ts/QUICKSTART).

By the way, after reinstalling it via curl command provided it updated my current version to the latest (0.3.3) and now the **uninstall** option is available.

Sorry for the inconvenience.
