### ISSUE TITLE
Default installation with `fuelup` on a fresh Apple architecture device seems to be installing binaries with wrong architecture

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/fuelup#177]
### Problem

I had a chance to use `fuelup` in an m1 environment without rosetta2 and the default installation with `fuelup` seems to be installing wrong architecture. But I can see that it is downloading the correct archive for the binaries, so this might be a problem in the sway repo CI as well. Here are the logs of installing the latest toolchain:

```
Downloading: forc fuel-core 
Adding component forc v0.23.0 to 'latest-aarch64-apple-darwin'
Fetching binary from https://github.com/FuelLabs/sway/releases/download/v0.23.0/forc-binaries-darwin_arm64.tar.gz
Unpacking and moving forc to /Users/kayagokalp/.fuelup/toolchains/latest-aarch64-apple-darwin/bin
Unpacking and moving forc-deploy to /Users/kayagokalp/.fuelup/toolchains/latest-aarch64-apple-darwin/bin
Unpacking and moving forc-run to /Users/kayagokalp/.fuelup/toolchains/latest-aarch64-apple-darwin/bin
Unpacking and moving forc-explore to /Users/kayagokalp/.fuelup/toolchains/latest-aarch64-apple-darwin/bin
Unpacking and moving forc-lsp to /Users/kayagokalp/.fuelup/toolchains/latest-aarch64-apple-darwin/bin
Unpacking and moving forc-fmt to /Users/kayagokalp/.fuelup/toolchains/latest-aarch64-apple-darwin/bin
Adding component fuel-core v0.10.1 to 'latest-aarch64-apple-darwin'
Fetching binary from https://github.com/FuelLabs/fuel-core/releases/download/v0.10.1/fuel-core-0.10.1-aarch64-apple-darwin.tar.gz
Unpacking and moving fuel-core to /Users/kayagokalp/.fuelup/toolchains/latest-aarch64-apple-darwin/bin
```

Once I try to run `forc` after this I see

```
Bad CPU type in executable (os error 86)
```

Is it possible that we are creating the archive in the wrong architecture in sway publish binaries job etc?

After installing rosetta2, I can run `forc` and double checked the running arch (by running `forc-deploy` so that the process hangs and I can see the running arch in the activity monitor), and it is Intel. I guess our native m1 binaries are still Intel based 🤔 If i build them myself they are running in Apple arch.

### Steps

1. Nuke all `fuelup` files and (if it is possible) rosetta2 installation
2. Install the latest toolchain using `fuelup`
3. Try to run `forc`

### Possible Solution(s)

It is highly possible that the problem is not with `fuelup` but with sway repo CI which builds the binaries and packs them(?). So I will also test directly getting binaries from release tags of the sway repo as a next step. If that is the case we may want to move this to `sway` repo

### Fuelup version

```console
`0.5.0`
```

### Installed components

```console
latest-aarch64-apple-darwin
  forc - Up to date : 0.23.0
  fuel-core - Up to date : 0.10.1
fuelup - Up to date : 0.5.0
```

**Comment by kayagokalp** [comment]
As a next exploration step, I downloaded [https://github.com/FuelLabs/sway/releases/download/v0.23.0/forc-binaries-darwin_arm64.tar.gz](https://github.com/FuelLabs/sway/releases/download/v0.23.0/forc-binaries-darwin_arm64.tar.gz) and placed them in my path. It seems like they are in Intel arch so I believe this is a problem with Sway CI. Opening up an issue there.

**Comment by bingcicle** [comment]
Since this seems to be an issue with the upstream `forc`, would it be safe to close this issue?
