### ISSUE TITLE
create helpers to print lines prefixed with whitespaces

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#182]
We have places in `fuelup show` and `fuelup check` where we'd like to show the hierarchy of components/plugins by prefixing a certain amount of whitespaces to stagger the output eg. we show forc-fmt as part of forc, for example. Right now we manually type in the spaces, but we can improve by having a fn to input the number of spaces we want instead.

**Comment by mitchmindtree** [comment]
I think the `format!` macro might already allow for this with one of its specifiers, e.g. https://doc.rust-lang.org/std/fmt/index.html#fillalignment.
