### ISSUE TITLE
Add CI for building, testing, publishing

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuelup#2]
Once we've got a bare-bones cargo project, we should prioritise setting up CI.

We'll likely want to publish the `fuelup` binary for each platform similar to how we publish `forc` for each platform too.

**Comment by binggh** [comment]
Issue is partially done in #8 and #9 since we are building/publishing there. Next up to set up testing.

Should we also publish `fuelup` to crates.io, or should binary releases be our only source of distribution? AFAIK `rustup` is only downloadable through the script found on rustup.rs

**Comment by mitchmindtree** [comment]
Hmmm good question. We might want to avoid encouraging that users acquire `fuelup` via `cargo install fuelup`, particularly if we plan on supporting the ability for `fuelup` to update itself?

**Comment by adlerjohn** [comment]
That's not a bad idea. That being said, we should reserve the `fuelup` crate (already reserved technically https://crates.io/crates/fuelup).

**Comment by binggh** [comment]
How do I transfer it over to the org btw?

**Comment by adlerjohn** [comment]
Make https://crates.io/users/fuel-bot a crate owner.

**Comment by binggh** [comment]
invited ⚡ ⛽
