### ISSUE TITLE
Proposal to add the ability for `fuelup` to list components that you have the ability to install on your current toolchain

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/fuelup#264]
### Problem you are trying to solve

I've been finding myself wanting the ability to write `fuelup component list` to see a list of possible components that I could install (and which version is `latest`).

### Solution you'd like

Currently my flow is to use `fuelup show` to get the current list of components that I _don't_ have installed, then `fuelup component add <name>` based on the list from the previous command. But remembering that flow feels a little unintuitive to me because `fuelup show` is semantically different than `fuelup component`, and also the description for `fuelup show` doesn't list "component": "Show the active and installed toolchains, as well as the host and fuelup home"

### Notes

Just a thought 😄

**Comment by bingcicle** [comment]
great suggestion :+1:! Definitely workable and would probably be useful for custom toolchains.

If this proposal is 1 command alone, I'm imagining something like this:

```
$ fuelup component list
forc (installed)
  installed: v0.29.0, latest: v0.31.0
fuel-core (installed)
  installed: v0.14.1 (latest)
forc-wallet
  latest: v0.1.2
```
We could also add a 2nd command to list available versions for a command, `fuelup component list <component>`. This should list all versions for the downloadable component, starting from the latest, and bolds + marks your currently installed version in your current toolchain:

```console
$ fuelup component list forc
forc
- 0.31.0 (latest)
- 0.30.1
- 0.30.0 (installed)
- 0.29.0
...
``` 

The reasoning for listing all versions would be that if we want to know what the latest version is, it might be likely that we want to know what other versions are available as well. We could show up to the 10 most recent versions, and have a flag to display all (like `fuelup component list forc --all`)

What do you think? cc @FuelLabs/tooling for any additional input

**Comment by mitchmindtree** [comment]
> What do you think? 

Sounds good!

> If this proposal is 1 command alone, I'm imagining something like this

Perhaps we should more clearly separate the installed and uninstalled components? E.g.

```console
$ fuelup component list
Installed:
  forc v0.31.0 (up-to-date)
  fuel-core v0.14.0 (latest: v0.14.1)
  ...
Available:
  forc-wallet (latest: v0.1.2)
  ...
```

> We could also add a 2nd command to list available versions for a command, fuelup component list <component>.

Looks good!

**Comment by emilyaherbert** [comment]
This all sounds good to me 👍 

> Perhaps we should more clearly separate the installed and uninstalled components?

This one feels solid 👍
