### ISSUE TITLE
Integrate fuel-Indexer binaries into fuelup 

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuelup#277]
### Problem you are trying to solve

- On the fuel-Indexer we just cut a release (v0.1.4) with support for more platforms 
- We would like to integrate this release’s binaries into fuelup
- The release is at https://github.com/FuelLabs/fuel-indexer/releases/tag/v0.1.4
- Ideally need to have this done by the end of our milestone on 11/30
  - The milestone issue https://github.com/FuelLabs/fuel-indexer/issues/295
- Definitely reach out to me with any questions/issues 

### Solution you'd like

- I would like Bing to work his fuelup magic to make this happen, or let me know how I can help with this work

**Comment by bingcicle** [comment]
this should be closed by #281 and the latest v0.13.0 release.
