### ISSUE TITLE
Provide a way to view SDK version compatibility for official toolchains

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuelup#289]
While `fuelup` cannot *ship* the SDK per se, it would be nice if we could at least provide a way of determining a version that is definitely compatible with a toolchain's version of `forc` and `fuel-core`.

We might do this by adding a special step that inspects the version of `fuels` used within the sway repo E2E tests when checking for a new `forc` version?

We can likely only achieve this nicely for the official toolchains, as there is nothing stopping a user from constructing a custom toolchain using versions of `forc` and `forc-client` with differing SDK versions for example.

**Comment by bingcicle** [comment]
Since the compatibility tests use the exact same workflow [job](https://github.com/FuelLabs/fuelup/blob/06a15b4c0560eacc88ce9ca374510183fdb59a81/.github/workflows/test-toolchain-compatibility.yml#L61-L69) as the one in the sway repo, it seems like we'd expect the `fuels` version to be inspectable from [here](https://github.com/FuelLabs/sway/blob/47423bf97be06c815bd4e0c882046be986911629/test/src/sdk-harness/Cargo.toml#L14). 

What should we do with this info though? Should `fuelup` eagerly detect the `fuels` version used in a project's `Forc.toml` whenever trying to compile with `forc`, and warn/fail in advance?

**Comment by mitchmindtree** [comment]
I think we should just allow for printing it somehow, e.g. maybe when we do `fuelup show` or similar?

Basically, as long as there's some way for the user to find out what *should* work based on their current toolchain. We don't have to do anything too fancy like add-to or validate `Cargo.toml` files or anything like that.

**Comment by bingcicle** [comment]
> I think we should just allow for printing it somehow, e.g. maybe when we do `fuelup show` or similar?

Sounds good - I was initially thinking this info could live in the channel as a top-level key-value pair, like so:

```toml
published_by = "..."
fuels_version = "0.31"
```

But `forc-wallet` has its own versioning of `fuels` as well. So perhaps we could have it within the individual package's table instead:

```toml
[pkg.forc]
version = "0.31.1"
fuels_version = "0.31"

# forc binaries links/hashes here
# ...

[pkg.fuel-core]
version = "0.14.1"
fuels_version = "0.31"

# ...
```

However this means that running `fuelup show` will now involve querying the channel for the `fuels_version`.

>  We don't have to do anything too fancy like edit or validate Cargo.toml files or anything like that.

Oops! I indeed meant Cargo.toml and not Forc.toml.

**Comment by mitchmindtree** [comment]
> But forc-wallet has its own versioning of fuels as well

Good catch! Having it per package sounds good.

Seeing as it can be unique per package and still function, perhaps we can just show the SDK version alongside the component (only if it depends on `fuels` of course) when listing components?

> However this means that running fuelup show will now involve querying the channel for the fuels_version.

Perhaps we could store this info locally somewhere when we install the toolchain to avoid the need to fetch?

**Comment by bingcicle** [comment]
Now that we have the store, would it be better to cache the `fuels` version in the store instead? In this way the compatible fuels version is tied to the component and not to the entire toolchain.

Here's how I imagine it to work:

1. user downloads a component. In the download phase `fuelup` will also check the dependencies for `fuels` dependency, and cache it in the store in the same directory as the binary - eg. if `forc-0.35.3` has a fuels dependency of `0.36`, the string `0.36` will be cached in a file called `fuels_version` in the same directory as the `forc` binary.
2. On calling `fuelup show`, fuelup show should now also store the mapping of component name->component version if showing the versions execute successfully.
3. Using the mapping, we find and display all the components with a cached `fuels_version` at the end of `fuelup show`.

Sample:

```
installed toolchains
--------------------
beta-3-x86_64-unknown-linux-gnu (default)
latest-x86_64-unknown-linux-gnu
latest-2023-01-18-x86_64-unknown-linux-gnu

active toolchain
-----------------
beta-3-x86_64-unknown-linux-gnu (default)
  forc : 0.35.3
    - forc-client
      - forc-deploy : 0.35.3
      - forc-run : 0.35.3
    - forc-doc : 0.35.3
    - forc-explore : 0.28.1
    - forc-fmt : 0.35.3
    - forc-index : Error getting version string
    - forc-lsp : 0.35.3
    - forc-tx : 0.35.3
    - forc-wallet : 0.2.0
  fuel-core : 0.17.3
  fuel-indexer : Error getting version string

fuels versions
---------------
forc-wallet : 0.36
forc : 0.36
```

Would this be better than pinning the versions to official toolchains?

**Comment by bingcicle** [comment]
On second thought, the above may not be such a great idea because there _can_ be releases of components that end up incompatible with `fuels`. Having it on the toolchain level makes sense.

**Comment by mitchmindtree** [comment]
Yeah this sounds fine - alternatively, you could keep a fuels version "cache" outside of the store by maintaining a separate directory of simple files that map from stores *hashes* to known `fuels` versions.

Ah I see there's a PR open :eyes:
