### ISSUE TITLE
Use `shellcheck` in CI to ensure `fuelup-init.sh` reliability

### ISSUE THREAD

**Issue by binggh** [FuelLabs/fuelup#31]
https://github.com/koalaman/shellcheck
https://github.com/ludeeus/action-shellcheck

Could be useful to ensure reliability of `fuelup-init.sh`

Edit: this should include a formatter as well.

**Comment by adlerjohn** [comment]
This is exactly what I used to clean up in #28!

**Comment by binggh** [comment]
TIL of this useful tool

**Comment by mitchmindtree** [comment]
TIL too, sounds like a great idea!
