### ISSUE TITLE
`fuelup` should download the latest toolchain

### ISSUE THREAD

**Issue by binggh** [FuelLabs/fuelup#4]
Ideally the minimum viable version of `fuelup` should simply download the latest stable release toolchain (`forc`, `fuel-core`) based on the user's OS or user input

**Comment by binggh** [comment]
Now that we almost have releases officially (once #12 is fixed) this issue should be soon clearable by updating `fuelup-init.sh` to curl the script, download the appropriate release and install `fuelup` along with the latest versions of `forc`, `forc-fmt`, `forc-lsp`, `forc-explore` and `fuel-core`

**Comment by adlerjohn** [comment]
Now that I think about it...should `fuelup` be able to update itself?

**Comment by binggh** [comment]
> Now that I think about it...should `fuelup` be able to update itself?

Yup! `rustup` does the same as well - `rustup update` updates all the installed toolchains, then updates itself. We can do something like `fuelup update` that does the same thing.

**Comment by adlerjohn** [comment]
Is this done?

**Comment by binggh** [comment]
Yup since it set out to do what it described - tracking the `self update` feature in #24
