### ISSUE TITLE
`fuelup` version tag isn't picked up correctly

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/fuelup#40]
Executing the following on my MBA M1 

`curl --proto '=https' --tlsv1.2 -sSf https://fuellabs.github.io/fuelup/fuelup-init.sh | sh -s install`

was resulting in the following:

```
cut: illegal option -- -
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
info: downloading installer
curl: (22) The requested URL returned error: 404 
fuelup: command failed: downloader https://github.com/FuelLabs/fuelup/releases/download/v/fuelup--aarch64-apple-darwin.tar.gz /var/folders/dr/s22m32g96ksgthk_4kby3mrh0000gn/T/tmp.FAirxTJB/fuelup.tar.gz aarch64-apple-darwin
```

by @binggh suggestion : changing `cut -c 1 --complement` to `cut -c 2-` in `fuelup-init.sh` seems like doing the trick.

**Comment by adlerjohn** [comment]
Interesting, I guess M1s don't have `--complement` for `cut`!
