### ISSUE TITLE
[WSL] Could not build download configs from channel 

### ISSUE THREAD

**Issue by Crescent617** [FuelLabs/fuelup#428]
### Problem

I'm using wsl2 on Win11.
When I run `fuelup toolchain install latest`, it raise `Could not build download configs from channel` error.

Env:
```
❯ fuelup --version
fuelup 0.19.0

❯ fuelup default
latest-x86_64-unknown-linux-gnu (default)
```

### Steps

1.  run `curl --proto '=https' --tlsv1.2 -sSf https://install.fuel.network/fuelup-init.sh | sh`, raise error:  `Could not build download configs from channel`
2. it seems only `fuelup` has been installed, no `forc, forc-client, forc-fmt, forc-lsp, forc-wallet`.
3. run `fuelup toolchain install latest`, it raise `Could not build download configs from channel` error.

### Fuelup version

```console
fuelup 0.19.0
```

### Installed components

```console
fuelup - Up to date : 0.19.0
```

**Comment by Crescent617** [comment]
```
❯ cargo run -- toolchain install latest
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/fuelup toolchain install latest`

Could not build download configs from channel. due to Could not read https://raw.githubusercontent.com/FuelLabs/fuelup/gh-pages/channel-fuel-latest.toml. due to
: Unexpected error: https://raw.githubusercontent.com/FuelLabs/fuelup/gh-pages/channel-fuel-latest.toml: Connection Failed: Connect error: Connection refused (o
s error 111)
```

**Comment by bingcicle** [comment]
Hey @Crescent617 - did you manage to find a solution to this issue?

**Comment by Crescent617** [comment]
Yes. i found the ip address of `raw.githubusercontent.com` in `ipaddress.com` and rewrite my local hosts file.
