### ISSUE TITLE
define `stable` toolchains and design a release process for `stable`

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#440]
Original issue: https://github.com/FuelLabs/fuelup/issues/66

Related: #81

The original issue encapsulates all default toolchains, from which 2 out of 3 are already live (`latest` and `nightly`). The remaining toolchain we have left is `stable`, but this is way too early to discuss.

We have to first decide on what exactly a `stable` toolchain means, and also design a release process for `stable`.

Currently, the `latest` toolchain depends on a very simple github action that checks for releases every hour, and updates the channel if needed. In the case of `forc` and `fuel-core`, compatibility tests are ran before the versions are bumped.

`nightly` toolchains are released every day at https://github.com/FuelLabs/sway-nightly-binaries, without any compatibility tests.

`stable` toolchains should probably be thought through once forc and its accompanying tools mature, but this should be a long time from now past mainnet.

**Comment by sdankel** [comment]
Going forward we are using `latest` as the latest stable release, so we don't need a separate `stable`. Related https://github.com/FuelLabs/fuelup/pull/506
