### ISSUE TITLE
support downloading plugins

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#5]
`fuelup` should also be able to download and install plugins supported natively by Fuel Labs.

**Comment by mitchmindtree** [comment]
I believe rustup distinguishes between sets of included plugins with the concept of "profiles":

https://rust-lang.github.io/rustup/concepts/profiles.html

Could be worth taking a similar approach.

**Comment by adlerjohn** [comment]
Note that currently all `forc-*` plugins that are in the Sway repo are bundled together into a single tarball, along with `forc` itself. External plugins such as `forc-wallet` are separate.

**Comment by Voxelot** [comment]
Do we have plans to setup a plugin registry?

**Comment by mitchmindtree** [comment]
No plans at the moment, for now I guess our ad-hoc plugin registry is:

```
cargo search --limit 100 "forc-" | grep -ie plugin
```
:smiling_face_with_tear: 

Currently a forc plugin is just an executable available on `PATH` that starts with `forc-` much like cargo "plugins", e.g. it doesn't even necessarily have to be a Rust program or expose a particular set of commands.

I wonder if there's a plugin registry/index out there for `cargo-*` programs that are known plugins aimed at "extending" cargo :thinking:

**Comment by bingcicle** [comment]
Closed in favour of #162 since official plugins are currently downloaded in one release within the sway repository.
