### ISSUE TITLE
Add a logging system for better reproducing bugs

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/fuelup#519]
From time to time we are faced with bugs that is generally related to the local system of the user which is really hard to reproduce. We should create a log dumping system so that we can request that from bug reporters. We should include various stuff that might be related to the system and fuelup. One example can be the `$PATH` variable another might be a check if fuelup or any other fuel binaries were installed via cargo or output of `which forc` etc.

cc @FuelLabs/tooling

**Comment by sdankel** [comment]
We could do this using the `tracing` crate.

**Comment by sdankel** [comment]
It would also be useful to log what command and arguments were used.
