### ISSUE TITLE
Deployed a simple contract using sway playground

### ISSUE THREAD

**Issue by sanchizzy** [FuelLabs/fuelup#572]
Deployed a simple contract language using the Fuel sway playground.
<img width="960" alt="image" src="https://github.com/FuelLabs/fuelup/assets/79314168/d76924bd-647a-462a-a79f-ae1c6ce88bf1">

Contract ID: 0x32a56800fb98baae2adbde60e3306b2b3e77fe2b593254002dc6e1c294e94fe1
Fuel address: fuel1jtwknknzgww0580p6nqglzas4qqmv6gcgn7k3hkuj3yy0kr3n64ss7assk

**Comment by shexinyi** [comment]
Is it  deployed in  testnet Beta5  now ?

**Comment by sanchizzy** [comment]
> Is it deployed in testnet Beta5 now ?

yes it is

**Comment by JoshuaBatty** [comment]
Closing, this isn't a tech issue related to fuelup
