### ISSUE TITLE
When will SWAP trading be added to the wallet?

### ISSUE THREAD

**Issue by shexinyi** [FuelLabs/fuelup#588]
### Problem you are trying to solve

Can i ask when will swap trading be added to the wallet?

### Solution you'd like

Can i ask when will swap trading be added to the wallet?

**Comment by JoshuaBatty** [comment]
Are you referring to forc-wallet or the fuel wallet browser extension? 

I think this question is better discussed on the forum https://forum.fuel.network/. Feel free to post over there. Closing as it doesn't related to fuelup.
