### ISSUE TITLE
Provide an option to configure user's path

### ISSUE THREAD

**Issue by binggh** [FuelLabs/fuelup#59]
`fuelup-init.sh` should ask for permission to configure the user's PATH, and work to add `/.fuelup/bin` to PATH if permitted. Default behaviour should still be to **not** alter PATH.

Perhaps, a message like this right at the beginning:

`fuelup has to download binaries into /.fuelup/bin. Can fuelup modify your PATH variable? (N/y)`

**Comment by adlerjohn** [comment]
The message should explain explicitly what modifying the PATH variable entails, so that the user can make an informed decision. There should also be a command line argument to both not-modify and modify silently.
