### ISSUE TITLE
Cannot download nightly

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/fuelup#593]
When running `fuelup toolchain install nightly` from a fresh install of fuelup, there is an error in `src/download`. The error is also seen when the toolchain is already set to nightly and then running `fuelup update`.

<img width="680" alt="Screenshot 2024-03-06 at 12 38 52 PM" src="https://github.com/FuelLabs/fuelup/assets/54727135/3b97e149-ed25-4d34-b7e7-acc6bc07f2b5">

**Comment by JoshuaBatty** [comment]
Thanks for the report! 

This should be working again now. It looks like the mac builds were skipped on the nightly job https://github.com/FuelLabs/fuelup/actions/runs/8165474011/job/22322679473

Manually re-running the Publish channel (nightly) action correctly builds for all targets.
