### ISSUE TITLE
Detect inconsistent versions between default toolchain and Forc manifest version

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#6]
`fuelup` should be able to do both these things:

- [x] Set the default toolchain version.
- [ ] Enable reading of the default toolchain version (so that `forc` can detect when you're using the wrong version that doesn't match what's configured in the manifest file).

As mentioned [here](https://github.com/FuelLabs/fuelup/issues/1#issuecomment-1137365618), this would probably require some design decisions on what constitutes a stable toolchain and how we reconcile `forc` and `fuel-core` compatibility

Update:

With https://github.com/FuelLabs/sway/pull/2405 now merged, we can detect inconsistent versions by matching with the minimum `forc-version` specified in the `Forc.toml`.

**Comment by bingcicle** [comment]
Since part 1 is already done with the introduction of the `fuelup default` command, I'm going to rename this issue and leave the 2nd one up as a task.

**Comment by sdankel** [comment]
This is done using `forc-toolchain.toml` (overrides)
