### ISSUE TITLE
Track code coverage

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/fuelup#640]
Track code coverage, ideally w/branch coverage, for fuelup repo. Possible using [`cargo llvm-cov`](https://github.com/taiki-e/cargo-llvm-cov)

**Comment by kayagokalp** [comment]
closed by #641

**Comment by mh6005** [comment]
Ok

در تاریخ چهارشنبه ۲۶ ژوئن ۲۰۲۴،‏ ۰۱:۱۸ Kaya Gökalp ***@***.***>
نوشت:
