### ISSUE TITLE
Delete fuelup folder when uninstalling

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/fuelup#651]

**Comment by alfiedotwtf** [comment]
We want the ability to uninstall:

- components
- toolkits
- fuelup itself

All look like they have the ability to be uninstalled. For this issue, `fuelup self uninstall` does delete the `fuelup` folder when unstalling, which was implemented in commit af125ff0

**Comment by sdankel** [comment]
Interesting, @LuizAsFight had an issue where he uninstalled fuelup but the folder was still there.

**Comment by alfiedotwtf** [comment]
@LuizAsFight if you see this happen again, please ping me and I'll take another look.

**Comment by LuizAsFight** [comment]
sounds good I'll let you know if it ever happens again, but my fuelup was installed lot of time ago so I guess it was something odd,
