### ISSUE TITLE
Improve `Usage` section to show how to use `--help`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuelup#67]
# Summary

When running `fuelup --help` it tells you to run `help` on any sub-command.
It does not tell you how to run the command.

Fix: Change usage to indicate that a user must run `fuelup <SUBCOMMAND> --help` instead of `fuelup --help <SUBCOMMAND>`

# Screenshots
![1](https://user-images.githubusercontent.com/103777923/173002708-777227ea-8488-4bc9-b397-0cbbe16b1506.png)

**Comment by adlerjohn** [comment]
This is standard Rust though. Generated automatically from `clap`. All Rust CLI tools that use `clap`, along with Cargo itself, behave this way. The instructions are actually completely explicit and unambiguous if you read them carefully.

**Comment by Braqzen** [comment]
> This is standard Rust CLI, generated automatically from `clap`. All Rust CLI tools that use `clap`, along with Cargo itself, behave this way.

Then they all need to be improved to be explicit.

**Comment by mitchmindtree** [comment]
This is not just a convention in Rust, but a convention in a lot of other unix-y CLI tools too.

E.g. I can do `nix --help` and it will show me all the commands etc like you'd expect. But I can also do `nix build --help`, an it will show me all the options etc for the `nix build` command, and so on.

That said, I agree it would be nice if tools showed that this could be done in the top-level default help output, as you're right that all these unix-y conventions aren't at all obvious to non-grey-beards and n00bs.

**Comment by JoshuaBatty** [comment]
I'm not convinced what we already have isn't sufficient. Closing.
