### ISSUE TITLE
Component not found in currently active toolchain 

### ISSUE THREAD

**Issue by UPON-2021** [FuelLabs/fuelup#681]
I am just learning at [OTC-swa-predicate project](https://github.com/FuelLabs/sway-applications/tree/master/OTC-swap-predicate). But I can't use any compoment of fuel.
![图片](https://github.com/user-attachments/assets/c90f60f6-9b25-4039-81f0-22bdca900a73)
![图片](https://github.com/user-attachments/assets/828206b2-0d4a-4080-b307-1c10cb06fd26)

The fuel-toolchain.toml is:
```
[toolchain]
channel = "nightly-2024-05-28"

[components]
forc = "0.60.0"
fuel-core = "0.26.0"
```

Fuelup show:
![图片](https://github.com/user-attachments/assets/739a9a6b-ca42-4565-aafd-ca6cca5a0882)

Files in `~/.fuelup/toolchains/nightly-2024-05-28-x86_64-unknown-linux-gnu/bin`
![图片](https://github.com/user-attachments/assets/76bb4e26-6564-4564-a1d9-074c9c1741f4)

**Comment by alfiedotwtf** [comment]
Thanks for the report. I have a few incoming PRs that should address this soon.

**Comment by alfiedotwtf** [comment]
Possibly related to #654

**Comment by alfiedotwtf** [comment]
Can you please `fuelup upgrade`. This should fix the issue you saw previously.

**Comment by UPON-2021** [comment]
Fixd!
