### ISSUE TITLE
Index version set for toolchain: `stable`

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#81]
3/3 of #66, ([discussion](https://github.com/FuelLabs/fuelup/issues/66#issuecomment-1153385665))

Before this issue can be tackled we need to first decide what __stable__ means in the context of the Fuel toolchain.

TODO:
- [ ] Use current `latest` channel as `stable` (#117)
- [ ] Support `fuelup toolchain install stable` in the CLI

**Comment by bingcicle** [comment]
After some re-consideration of our current approach of testing and distributing the `latest` toolchain (thanks to #95), as well as taking into consideration how often devs might want access to the latest release asap, a decent solution right now would be to distribute what we currently consider as `latest`, as the `stable` toolchain instead.

The reason they can be considered as stable is because they've passed integration tests between each other, and therefore the releases should be behaving as correctly with each other as we can possibly assure. Of course, there might be unknown bugs that we might not know of, but it is probably fair to distribute something as `stable` knowing that comprehensive test suites passed for known bugs, failure patterns, success behaviours, etc.

`latest` should instead be the toolchain that _always_ contains the latest binaries, regardless of whether tests passed, because of how frequent users need the latest versions to get the latest changes/bug fixes.

**Comment by mitchmindtree** [comment]
Just an update: soon after @bingcicle's last comment we decided to keep the existing `latest` terminology. See [this table](https://github.com/FuelLabs/fuelup/issues/118#issue-1317695819) for a very brief/rough overview of plans for each channel.

**Comment by bingcicle** [comment]
closing this in favour of #440
